//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_facturas_pendientes_contabilizacion
    {
        public int factura { get; set; }
        public int cliente { get; set; }
        public int rut { get; set; }
        public int monto { get; set; }
    }
}
