//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class fecha
    {
        public int Id_fecha { get; set; }
        public Nullable<System.DateTime> Fecha1 { get; set; }
        public string Mes { get; set; }
        public string Año { get; set; }
        public Nullable<int> Mes_n { get; set; }
        public Nullable<int> Trimestre { get; set; }
        public Nullable<int> Semestre { get; set; }
    }
}
