//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class folios_factura
    {
        public int Id_folios { get; set; }
        public string tipo { get; set; }
        public string doc { get; set; }
        public Nullable<int> fol_in { get; set; }
        public Nullable<int> fol_fin { get; set; }
        public Nullable<int> ult_fol { get; set; }
    }
}
