//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class folio4_clientes
    {
        public int Id_folio { get; set; }
        public Nullable<double> folio { get; set; }
        public string numero_pedido { get; set; }
        public string cliente { get; set; }
        public string rut { get; set; }
        public string linea_credito { get; set; }
        public string cond { get; set; }
        public string forma_de_pago { get; set; }
        public string ejec_cobranza { get; set; }
    }
}
