//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class folio_compra
    {
        public int Id_folio_compra { get; set; }
        public Nullable<double> folio_compra1 { get; set; }
        public Nullable<double> numero_pedido { get; set; }
        public string proveedor { get; set; }
    }
}
