//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_emails
    {
        public int Id_log_emails { get; set; }
        public Nullable<double> pedido { get; set; }
        public string factura { get; set; }
        public string rut_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string email { get; set; }
    }
}
