//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class nc_cen
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string nota_credito { get; set; }
        public string factura { get; set; }
        public string codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> total_detalle { get; set; }
        public string rut { get; set; }
        public string razon_social { get; set; }
        public Nullable<double> cantidad_detalle { get; set; }
        public Nullable<double> precio_rollo { get; set; }
        public string usuario { get; set; }
        public Nullable<double> venta_neta { get; set; }
        public int id_nc_detalle { get; set; }
    }
}
