//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_credito_detalle2
    {
        public int id_nc_detalle { get; set; }
        public string n_factura { get; set; }
        public string nota_credito { get; set; }
        public string codigo { get; set; }
        public Nullable<double> precio_rollo { get; set; }
        public Nullable<double> cantidad_detalle { get; set; }
        public Nullable<double> total_detalle { get; set; }
        public string folio_nc { get; set; }
    }
}
