//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_credito3
    {
        public int id_nc { get; set; }
        public string n_factura { get; set; }
        public string nota_credito { get; set; }
        public string razon_social { get; set; }
        public string rut { get; set; }
        public string accion { get; set; }
        public string error1 { get; set; }
        public string observaciones { get; set; }
        public string motivo { get; set; }
        public Nullable<double> venta_neta { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> total { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
    }
}
