//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.usuarioweb = new HashSet<usuarioweb>();
        }
    
        public int idPerfil { get; set; }
        public Nullable<sbyte> Venta { get; set; }
        public Nullable<sbyte> Administracion { get; set; }
        public Nullable<sbyte> Cobranza { get; set; }
        public Nullable<sbyte> Logistica { get; set; }
        public Nullable<sbyte> ServicioTecnico { get; set; }
        public Nullable<sbyte> AdminII { get; set; }
        public Nullable<sbyte> Compras { get; set; }
        public Nullable<sbyte> Tickets { get; set; }
    
        public virtual ICollection<usuarioweb> usuarioweb { get; set; }
    }
}
