//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        public int Id_proveedores { get; set; }
        public string tipo_prov { get; set; }
        public string rut { get; set; }
        public string razon_social { get; set; }
        public string giro { get; set; }
        public string pais { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string observacion { get; set; }
        public string nombre_comer { get; set; }
        public string cargo_comer { get; set; }
        public string telefono_comer { get; set; }
        public string email_comer { get; set; }
    }
}
