//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_llamada
    {
        public int Id_registro_llamada { get; set; }
        public string Cliente { get; set; }
        public string atendio { get; set; }
        public string motivo { get; set; }
        public string telefono { get; set; }
        public string tipo_llamada { get; set; }
        public Nullable<System.TimeSpan> llamada_iniciada { get; set; }
        public Nullable<System.TimeSpan> llamada_finalizada { get; set; }
        public Nullable<System.TimeSpan> duracion { get; set; }
        public string estado_de_linea { get; set; }
        public string importancia { get; set; }
        public string informe { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public string tipo { get; set; }
        public string tipo_medio { get; set; }
        public Nullable<double> folio { get; set; }
    }
}
