//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta_guia
    {
        public int Id_ruta { get; set; }
        public string usuario { get; set; }
        public string chofer { get; set; }
        public string vehiculo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<double> n_pedido { get; set; }
        public string ejecutivo { get; set; }
        public string direccion { get; set; }
        public string comuna { get; set; }
        public Nullable<double> folio_ruta { get; set; }
        public string tipo { get; set; }
        public string cliente { get; set; }
    }
}
