//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int id { get; set; }
        public string asunto { get; set; }
        public string departamento { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public string nombre { get; set; }
        public string prioridad { get; set; }
    }
}
