//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class sustituto
    {
        public int Id_sustituto { get; set; }
        public string codigo1 { get; set; }
        public string descripcion1 { get; set; }
        public string codigo2 { get; set; }
        public string descripcion2 { get; set; }
    }
}
