//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioweb
    {
        public int cod_usuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public int Perfil_idPerfil { get; set; }
    
        public virtual perfil perfil { get; set; }
    }
}
