//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papiro_Web.ServicioAutenticacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAutenticacion.IAutenticacion")]
    public interface IAutenticacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/LoginUsuario", ReplyAction="http://tempuri.org/IAutenticacion/LoginUsuarioResponse")]
        string LoginUsuario(string nombre, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/LoginUsuario", ReplyAction="http://tempuri.org/IAutenticacion/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<string> LoginUsuarioAsync(string nombre, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionChannel : Papiro_Web.ServicioAutenticacion.IAutenticacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<Papiro_Web.ServicioAutenticacion.IAutenticacion>, Papiro_Web.ServicioAutenticacion.IAutenticacion {
        
        public AutenticacionClient() {
        }
        
        public AutenticacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginUsuario(string nombre, string password) {
            return base.Channel.LoginUsuario(nombre, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginUsuarioAsync(string nombre, string password) {
            return base.Channel.LoginUsuarioAsync(nombre, password);
        }
    }
}
