//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorizacion_otros
    {
        public int id_autorizacion { get; set; }
        public Nullable<int> id_tipo_doc { get; set; }
        public string tipo_doc { get; set; }
        public Nullable<int> numero_doc { get; set; }
        public Nullable<int> id_tipo_aut { get; set; }
        public string tipo_aut { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    }
}
