//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloqueo
    {
        public int Id_bloqueo { get; set; }
        public string usuario { get; set; }
        public string rut { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public string bloqueo_desbloqueo { get; set; }
        public string senal_advertencia { get; set; }
        public string razon { get; set; }
    }
}
