//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int id_clientes { get; set; }
        public string rut { get; set; }
        public string clientes1 { get; set; }
        public string direccion { get; set; }
        public string comuna { get; set; }
        public string telefonos { get; set; }
        public string contacto_comercial { get; set; }
        public string cargo_contacto_comercial { get; set; }
        public string telefonos_contacto { get; set; }
        public string email_contacto_comercial { get; set; }
        public string contacto_pago_proveedores { get; set; }
        public string cargo_contacto_pago { get; set; }
        public string telefonos_cargo_contacto { get; set; }
        public string email_contacto_pago { get; set; }
        public string cond { get; set; }
        public string forma_de_pago { get; set; }
        public string ejec_digital { get; set; }
        public string ejec_media { get; set; }
        public string ejec_led { get; set; }
        public string ejec_mac { get; set; }
        public string direccion_despacho { get; set; }
        public string email_despacho { get; set; }
        public string telefonos_despacho { get; set; }
        public string contacto_despacho { get; set; }
        public string telefono_despacho { get; set; }
        public string senal_advertencia { get; set; }
        public string estado { get; set; }
        public string linea_credito { get; set; }
        public string dicom { get; set; }
        public string fecha_ingreso { get; set; }
        public string observacion { get; set; }
        public string maquinas { get; set; }
        public string email_contacto2 { get; set; }
        public string actualizado { get; set; }
        public string giro { get; set; }
        public string email_contacto_despacho2 { get; set; }
        public string referencia { get; set; }
        public string ficha_cliente { get; set; }
        public string encargado_produccion { get; set; }
        public string maquina16 { get; set; }
        public string maquina18 { get; set; }
        public string maquina320 { get; set; }
        public string ejec_new { get; set; }
        public string ejec_cobranza { get; set; }
    }
}
