//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigos4
    {
        public int id_codigos { get; set; }
        public string Codigo { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public string Tipo_1 { get; set; }
        public string medidas { get; set; }
        public Nullable<double> unid_paquete { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> area { get; set; }
        public string descripcion_2 { get; set; }
        public string area_negocio { get; set; }
        public string proveedor { get; set; }
        public string mapa { get; set; }
        public string descripcion_3 { get; set; }
        public string obs { get; set; }
        public string familia { get; set; }
        public string familia_2 { get; set; }
        public string familia_3 { get; set; }
        public Nullable<double> stock { get; set; }
        public Nullable<double> medida_unid { get; set; }
        public Nullable<double> Precio_lista { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public Nullable<double> precio_max { get; set; }
        public Nullable<double> precio_min { get; set; }
        public Nullable<double> activo { get; set; }
        public string Categoria { get; set; }
        public string Categoria2 { get; set; }
    }
}
