//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_agrupadas
    {
        public int Id_documento { get; set; }
        public Nullable<int> Id_proveedor { get; set; }
        public string PAI { get; set; }
        public string folio_pedido { get; set; }
        public string folio_proforma { get; set; }
        public string folio_invoice { get; set; }
        public Nullable<System.DateTime> eta_estimado { get; set; }
        public Nullable<System.DateTime> eta_real { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string tipo_moneda { get; set; }
        public string certifica { get; set; }
    }
}
