//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_items
    {
        public int Id_item { get; set; }
        public Nullable<int> Id_documento { get; set; }
        public Nullable<int> pos { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string cant_ped { get; set; }
        public string cant_pro { get; set; }
        public string pre_pro { get; set; }
        public string cant_inv { get; set; }
        public string pre_inv { get; set; }
        public string certifica { get; set; }
        public string obs { get; set; }
    }
}
