//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta_despacho_3
    {
        public int ID { get; set; }
        public Nullable<double> Ruta { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> N__Pedido { get; set; }
        public string N__Documento { get; set; }
        public string Cliente { get; set; }
        public string Ejecutivo { get; set; }
        public string Chofer { get; set; }
        public string Vehiculo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora_Pedido { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public Nullable<System.DateTime> Hola_Llegada { get; set; }
    }
}
