//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta_despacho2
    {
        public int Id_ventas { get; set; }
        public string cliente { get; set; }
        public Nullable<double> numero_pedido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_act { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> venta_neta { get; set; }
        public Nullable<double> venta_iva { get; set; }
        public Nullable<double> venta_total { get; set; }
        public string indicador_despacho { get; set; }
        public int Expr1 { get; set; }
    }
}
