//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class encargado_rutas
    {
        public int Correlativo_de_ruta { get; set; }
        public string Usuario_de_ruta { get; set; }
        public string Chofer_de_ruta { get; set; }
        public string Vehículo_de_ruta { get; set; }
        public Nullable<System.DateTime> Fecha_de_ruta { get; set; }
        public Nullable<System.TimeSpan> Hora_de_ruta { get; set; }
        public Nullable<double> Número_de_pedido_de_ruta { get; set; }
        public string Ejecutivo_de_ruta { get; set; }
        public Nullable<double> Folio_de_ruta { get; set; }
        public Nullable<int> Folio_de_retiro_de_documento { get; set; }
        public string Feactura_de_retiro_de_documento { get; set; }
        public string RUT_de_retiro_de_documento { get; set; }
        public string CLiente_de_retiro_de_documento { get; set; }
        public Nullable<System.DateTime> Fecha_de_retiro_de_documento { get; set; }
        public string Usuario_de_retiro_de_documento { get; set; }
    }
}
