//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_cen
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Factura { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> venta_neta { get; set; }
        public Nullable<double> venta_iva { get; set; }
        public Nullable<double> venta_total { get; set; }
        public string rut { get; set; }
        public string cliente { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<int> precio_cliente { get; set; }
        public string toma_pedido { get; set; }
        public string forma_pago { get; set; }
        public Nullable<double> SumaDeventa_neta { get; set; }
        public int id_ventas { get; set; }
    }
}
