//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class folio_nc3
    {
        public int Id_folio_nc { get; set; }
        public string folio { get; set; }
        public string nota_credito { get; set; }
        public string factura { get; set; }
        public string cliente { get; set; }
        public string con_venta { get; set; }
        public string con_prod { get; set; }
        public string obs_venta { get; set; }
        public string con_material { get; set; }
        public string con_desp { get; set; }
        public string obs_logistica { get; set; }
        public string con_inv { get; set; }
        public string obs_serv { get; set; }
        public string autoriza_venta { get; set; }
        public string autoriza_logistica { get; set; }
        public string autoriza_serv { get; set; }
        public string motivo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> fecha_reclamo { get; set; }
        public string contacto { get; set; }
        public string respuesta { get; set; }
    }
}
