//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class folio_fecha7
    {
        public int Id_folio { get; set; }
        public Nullable<double> folio { get; set; }
        public string numero_pedido { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string toma_pedido { get; set; }
        public string comuna_despacho { get; set; }
        public string direccion_despacho { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<double> SumaDeventa_neta { get; set; }
    }
}
