//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class guias_despachos
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public string RUT { get; set; }
        public string Senal_de_advertencia { get; set; }
        public string Codigo_de_producto { get; set; }
        public string Descripcion { get; set; }
        public string Medidas { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Neto { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> Total { get; set; }
        public string Condicion { get; set; }
        public string Forma_de_pago { get; set; }
        public string Ejecutivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Solicitado { get; set; }
        public string Comuna { get; set; }
        public string Direccion { get; set; }
        public string Observacion { get; set; }
        public string Tipo_documento { get; set; }
        public Nullable<double> Folio_guia { get; set; }
        public string Numero_de_guia { get; set; }
        public string Factura { get; set; }
    }
}
