//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_solicitud_ticket
    {
        public int id { get; set; }
        public string comentario { get; set; }
        public string imagen { get; set; }
        public System.DateTime ingresado { get; set; }
        public string usuario { get; set; }
        public int solicitud_id { get; set; }
    }
}
