//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_compra
    {
        public int Id_nota_compra { get; set; }
        public Nullable<double> folio_compra { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public Nullable<System.DateTime> hora_compra { get; set; }
        public string nombre_ejecutivo { get; set; }
        public string pai_cn { get; set; }
    }
}
