//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class observaciones_llegada
    {
        public int Id_observaciones { get; set; }
        public string pendiente { get; set; }
        public Nullable<double> folio_ruta { get; set; }
        public string tipo { get; set; }
        public Nullable<double> num_doc { get; set; }
        public string observacion { get; set; }
        public string condicion_pago { get; set; }
        public string cumplimiento { get; set; }
    }
}
