//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class const113_papiroEntities : DbContext
    {
        public const113_papiroEntities()
            : base("name=const113_papiroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alerta_precios> alerta_precios { get; set; }
        public DbSet<autorizacion_otros> autorizacion_otros { get; set; }
        public DbSet<bloqueo> bloqueo { get; set; }
        public DbSet<cartera> cartera { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<codigos> codigos { get; set; }
        public DbSet<codigos3> codigos3 { get; set; }
        public DbSet<codigos4> codigos4 { get; set; }
        public DbSet<codigos44> codigos44 { get; set; }
        public DbSet<complementarios> complementarios { get; set; }
        public DbSet<compras> compras { get; set; }
        public DbSet<compras_doc> compras_doc { get; set; }
        public DbSet<compras_items> compras_items { get; set; }
        public DbSet<contacto_venta> contacto_venta { get; set; }
        public DbSet<contacto_venta1> contacto_venta1 { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<despachos> despachos { get; set; }
        public DbSet<facturas> facturas { get; set; }
        public DbSet<facturas3> facturas3 { get; set; }
        public DbSet<familia_complementaria> familia_complementaria { get; set; }
        public DbSet<familia_complementaria1> familia_complementaria1 { get; set; }
        public DbSet<fecha> fecha { get; set; }
        public DbSet<folio> folio { get; set; }
        public DbSet<folio_compra> folio_compra { get; set; }
        public DbSet<folio_guias> folio_guias { get; set; }
        public DbSet<folio_nc> folio_nc { get; set; }
        public DbSet<folio_nc3> folio_nc3 { get; set; }
        public DbSet<folio_ruta> folio_ruta { get; set; }
        public DbSet<folio3> folio3 { get; set; }
        public DbSet<folio4> folio4 { get; set; }
        public DbSet<folios_factura> folios_factura { get; set; }
        public DbSet<guias_despacho> guias_despacho { get; set; }
        public DbSet<guias_facturar> guias_facturar { get; set; }
        public DbSet<historial_solicitud_ticket> historial_solicitud_ticket { get; set; }
        public DbSet<llegada_ruta> llegada_ruta { get; set; }
        public DbSet<llegada_ruta2> llegada_ruta2 { get; set; }
        public DbSet<log_emails> log_emails { get; set; }
        public DbSet<nota_compra> nota_compra { get; set; }
        public DbSet<nota_credito> nota_credito { get; set; }
        public DbSet<nota_credito_detalle> nota_credito_detalle { get; set; }
        public DbSet<nota_credito_detalle3> nota_credito_detalle3 { get; set; }
        public DbSet<nota_credito3> nota_credito3 { get; set; }
        public DbSet<notas_de_pedido> notas_de_pedido { get; set; }
        public DbSet<notas_de_pedido_val> notas_de_pedido_val { get; set; }
        public DbSet<notas_de_pedido_val_aut> notas_de_pedido_val_aut { get; set; }
        public DbSet<notas_de_pedido_val_guias> notas_de_pedido_val_guias { get; set; }
        public DbSet<notas_de_pedido_val_rech> notas_de_pedido_val_rech { get; set; }
        public DbSet<notas_de_pedido3> notas_de_pedido3 { get; set; }
        public DbSet<notas_guias> notas_guias { get; set; }
        public DbSet<numero_pedido> numero_pedido { get; set; }
        public DbSet<observaciones_llegada> observaciones_llegada { get; set; }
        public DbSet<observaciones_llegada1> observaciones_llegada1 { get; set; }
        public DbSet<ofertas> ofertas { get; set; }
        public DbSet<programacion_llamadas> programacion_llamadas { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<reemprimir> reemprimir { get; set; }
        public DbSet<reg_cheques> reg_cheques { get; set; }
        public DbSet<registro_de_pagos4> registro_de_pagos4 { get; set; }
        public DbSet<registro_llamada> registro_llamada { get; set; }
        public DbSet<registro_pagos> registro_pagos { get; set; }
        public DbSet<registro_pagos3> registro_pagos3 { get; set; }
        public DbSet<registro_pagos4> registro_pagos4 { get; set; }
        public DbSet<registro_reemitir> registro_reemitir { get; set; }
        public DbSet<retiro_documentos> retiro_documentos { get; set; }
        public DbSet<ruta> ruta { get; set; }
        public DbSet<ruta1> ruta1 { get; set; }
        public DbSet<solicitud> solicitud { get; set; }
        public DbSet<stock> stock { get; set; }
        public DbSet<sustituto> sustituto { get; set; }
        public DbSet<tabla_asociar> tabla_asociar { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<usuario_adm> usuario_adm { get; set; }
        public DbSet<venta_guias> venta_guias { get; set; }
        public DbSet<venta_mod> venta_mod { get; set; }
        public DbSet<venta4> venta4 { get; set; }
        public DbSet<venta41> venta41 { get; set; }
    }
}
