//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class programacion_llamadas
    {
        public int Id_programacion { get; set; }
        public Nullable<System.DateTime> fecha_actual { get; set; }
        public Nullable<System.DateTime> fecha_programada { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> folio { get; set; }
        public string hecho { get; set; }
    }
}
