//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_pago_consulta
    {
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ANO { get; set; }
        public string MES { get; set; }
        public string DIA { get; set; }
        public string CODIGO { get; set; }
        public string OPERACIÓN { get; set; }
        public string BANCO { get; set; }
        public string SERIE { get; set; }
        public string FACTURA { get; set; }
        public Nullable<double> TOTAL_ADEUDADO { get; set; }
        public Nullable<double> MONTO { get; set; }
        public Nullable<double> DIFERENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_CHEQUE { get; set; }
        public Nullable<int> ANO_DOC { get; set; }
        public Nullable<int> MES_DOC { get; set; }
        public Nullable<int> DIA_DOC { get; set; }
        public string PENDIENTE { get; set; }
        public string ESTADO { get; set; }
        public string E_FACT { get; set; }
        public Nullable<double> MONT { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public string Expr1 { get; set; }
        public string Expr3 { get; set; }
    }
}
