//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id_stock { get; set; }
        public string Codigo { get; set; }
        public string Tipo_1 { get; set; }
        public string Tipo_2 { get; set; }
        public string Medida { get; set; }
        public Nullable<double> ctda_anter { get; set; }
        public Nullable<double> ctda_actual { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> area { get; set; }
        public Nullable<double> mt_totales { get; set; }
        public string observacion { get; set; }
    }
}
