//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_adm
    {
        public int Id_usuario { get; set; }
        public string tipo_nombre { get; set; }
        public string usuario { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public string modulo_nombre { get; set; }
        public Nullable<int> modulo_id { get; set; }
    }
}
