//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta_mod
    {
        public int Id_ventas { get; set; }
        public string cliente { get; set; }
        public string rut { get; set; }
        public string medidas { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> area_calc { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> area_total { get; set; }
        public Nullable<double> venta_rollo { get; set; }
        public Nullable<double> unit_venta_m2 { get; set; }
        public Nullable<double> venta_neta { get; set; }
        public Nullable<double> venta_iva { get; set; }
        public Nullable<double> venta_total { get; set; }
        public string ejecutivo { get; set; }
        public Nullable<System.DateTime> fecha_act { get; set; }
        public Nullable<double> numero_folio { get; set; }
        public Nullable<double> precio_cliente { get; set; }
    }
}
